### Registration
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Rawat",
    "email": "rawat@anurag.edu.in",
    "password": "securePassword123",
    "role": "USER"
}

### Login
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "kapish@anurag.edu.in",
    "password": "securePassword123"
}

### Logout
POST http://localhost:4000/logout