### Test 1: Successful Registration
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Rawat",
    "email": "rawat@anurag.edu.in",
    "password": "securePassword123",
    "role": "USER"
}

### Test 2: Fail - Wrong Email Domain (Regex Test)
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Stranger",
    "email": "hacker@gmail.com",
    "password": "password123",
    "role": "USER"
}

### Test 3: Fail - Invalid Role
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "AdminGuy",
    "email": "admin@anurag.edu.in",
    "password": "password123",
    "role": "SUPERUSER"
}